# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'finvuauthsdkdemoswiftui' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for finvuauthsdkdemoswiftui

  pod 'FinvuAuthenticationSDK', :git => 'https://github.com/Cookiejar-technologies/finvu-auth-sdk-ios.git',:branch => 'feat/sdk-publishing', tag: 'v0.1.2'
end
