default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "finvuauthsdkdemoswiftui.xcodeproj")

    build_app(
      workspace: "finvuauthsdkdemoswiftui.xcworkspace",
      scheme: "finvuauthsdkdemoswiftui",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.finvu.authsdkdemo" => "Finvu Auth SDK Demo app profile"
        }
      }
    )
  end
end
